baseURL: https://drishti-hoskote.netlify.app/
languageCode: en-us
title: Portfolio website for Drishti Hoskote
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Welcome to my portfolio! Learn more about me and the projects I've worked on :)
    title: Hi, I'm Drishti!
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        #street: 
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: dhoskote.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 7379783719
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/DrishtiHoskote
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/drishti.hoskote
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/drishti1607/
      - icon: fa-github
        label: GitHub
        url: https://github.com/drishti1607
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/drishti-hoskote/
  image: ''
  name: Drishti Hoskote
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/about_me
      - name: Blogs
        url: blogs
    menu: Menu
    subtitle: Portfolio Website
    title: Drishti Hoskote
  tiles:
    enable: yes
    showcase:
      - image: IMG_2059.JPG
        subtitle: Get to know me better!
        title: About Me
        url: blogs/about_me
      - image: pic02.jpg
        subtitle: Read about my experiences
        title: Resume
        url: blogs/resume.pdf
      - image: pic03.jpg
        subtitle: Analysis of the Leave Share % and Electoral Results 
        title: Brexit Analysis
        url: blogs/brexit_analysis
      - image: pic04.jpg
        subtitle: Analysing weather anomalies
        title: Climate and Temperature Change Analysis
        url: blogs/climate_analysis
      - image: pic05.jpg
        subtitle: Analysis of trends in rents in the Bay Area
        title: Rents in the Bay Area
        url: blogs/sa_rents
      - image: pic06.jpg
        subtitle: Analysis of Biden's Approval Ratings
        title: US Elections Approval Margins
        url: blogs/biden_approval_rating
  two:
    buttonText: Projects
    enable: yes
    subtitle: "Consulting | Product Management | Fintech | Phsychology"
    title: Areas of Interest
    url: blogs
